# frozen_string_literal: true

require_relative "../fs"
require_relative "../platform"

module Bundler2
  module Installer
    module Linker
      module_function

      # Link a single extracted gem into .bundle/ruby/{version}/
      # prepared_gem: PreparedGem struct (spec, extracted_path, gemspec, from_cache)
      # bundle_path:  root .bundle/ directory
      def link(prepared_gem, bundle_path)
        ruby_dir = ruby_install_dir(bundle_path)
        spec = prepared_gem.spec
        full_name = spec_full_name(spec)

        # 1. Link gem files into gems/{full_name}/
        gem_dest = File.join(ruby_dir, "gems", full_name)
        unless Dir.exist?(gem_dest)
          FS.hardlink_tree(prepared_gem.extracted_path, gem_dest)
        end

        # 2. Write gemspec into specifications/
        write_gemspec(prepared_gem, ruby_dir, full_name)

        # 3. Create binstubs for executables
        write_binstubs(prepared_gem, ruby_dir, gem_dest)
      end

      # Link multiple gems. Thread-safe — each link is independent.
      def link_batch(prepared_gems, bundle_path)
        prepared_gems.each { |pg| link(pg, bundle_path) }
      end

      # --- private helpers ---

      def write_gemspec(prepared_gem, ruby_dir, full_name)
        spec_dir = File.join(ruby_dir, "specifications")
        FS.mkdir_p(spec_dir)
        spec_path = File.join(spec_dir, "#{full_name}.gemspec")
        return if File.exist?(spec_path)

        content = if prepared_gem.gemspec.is_a?(String)
                    prepared_gem.gemspec
                  elsif prepared_gem.gemspec.respond_to?(:to_ruby)
                    prepared_gem.gemspec.to_ruby
                  else
                    minimal_gemspec(prepared_gem.spec, full_name)
                  end

        FS.atomic_write(spec_path, content)
      end

      def write_binstubs(prepared_gem, ruby_dir, gem_dir)
        # Look for executables declared in the gemspec
        executables = extract_executables(prepared_gem)
        return if executables.empty?

        bin_dir = File.join(ruby_dir, "bin")
        FS.mkdir_p(bin_dir)

        executables.each do |exe_name|
          binstub_path = File.join(bin_dir, exe_name)
          next if File.exist?(binstub_path)

          spec = prepared_gem.spec
          content = <<~RUBY
            #!/usr/bin/env ruby
            # frozen_string_literal: true
            #
            # This file was generated by bundler2 for #{spec_full_name(spec)}
            #
            gem "#{spec.name}", "#{spec.version}"
            load Gem.bin_path("#{spec.name}", "#{exe_name}", "#{spec.version}")
          RUBY

          FS.atomic_write(binstub_path, content)
          File.chmod(0o755, binstub_path)
        end
      end

      def extract_executables(prepared_gem)
        gemspec = prepared_gem.gemspec
        if gemspec.respond_to?(:executables)
          Array(gemspec.executables)
        elsif gemspec.is_a?(Hash) && gemspec[:executables]
          Array(gemspec[:executables])
        else
          []
        end
      end

      def minimal_gemspec(spec, full_name)
        <<~RUBY
          # frozen_string_literal: true
          Gem::Specification.new do |s|
            s.name = #{spec.name.inspect}
            s.version = #{spec.version.to_s.inspect}
            s.platform = #{platform_str(spec).inspect}
            s.authors = ["bundler2"]
            s.summary = "Installed by bundler2"
          end
        RUBY
      end

      def spec_full_name(spec)
        name = spec.name
        version = spec.version
        plat = platform_str(spec)
        base = "#{name}-#{version}"
        (plat == "ruby" || plat.empty?) ? base : "#{base}-#{plat}"
      end

      def platform_str(spec)
        p = spec.respond_to?(:platform) ? spec.platform : nil
        p.nil? ? "ruby" : p.to_s
      end

      def ruby_install_dir(bundle_path)
        File.join(bundle_path, "ruby", RUBY_VERSION.split(".")[0, 2].join(".") + ".0")
      end

      private_class_method :write_gemspec, :write_binstubs, :extract_executables,
                           :minimal_gemspec, :spec_full_name, :platform_str, :ruby_install_dir
    end
  end
end
